# Stage 1: Build Angular App
FROM node:20.12.1 AS angular

WORKDIR /app

# Copiar los archivos necesarios para la instalación
COPY package*.json ./
RUN npm install
RUN npx ngcc --properties es2024 browser module main --first-only --create-ivy-entry-points

# Compilar la aplicación Angular
COPY . .
RUN npm run build --prod

# Stage 2: Serve with NGINX
FROM nginx:1.27.0-alpine

# Copiar el archivo de configuración personalizado de NGINX
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar la salida del build de Angular al servidor NGINX
COPY --from=angular /app/dist/front/ /usr/share/nginx/html

# Exponer el puerto para NGINX
EXPOSE 80